Log bad pathnames (via repr()) instead of crashing entirely
 - Something in the PIM tree is making the script crash like this:
	  File "/home/api/kapidox/src/kapidox/preprocessing.py", line 101, in create_metainfo
	    metainfo_file = os.path.join(path, 'metainfo.yaml')
	  File "/usr/lib/python-exec/python2.7/../../../lib64/python2.7/posixpath.py", line 73, in join
	    path += '/' + b
	UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 88: ordinal not in range(128)
	 ** FATAL ERROR during script: not updated. **
   So log the pathname that does that and carry on, instead of not
   updating the API at all.